;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagTableList=/Game/JWGAS/Blueprint/GameData/GameplayTag/DT_Tag_Event.DT_Tag_Event
+GameplayTagTableList=/Game/JWGAS/Blueprint/GameData/GameplayTag/DT_Tag_Character.DT_Tag_Character
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Character.State.Attacking",NewTagName="Character.State.IsAttacking")
+GameplayTagRedirects=(OldTagName="Character.State.Dodge",NewTagName="Character.State.IsDodge")
+GameplayTagRedirects=(OldTagName="Player.Weapon.DualBlade",NewTagName="Player.Weapon.DualBladeL")
+GameplayTagRedirects=(OldTagName="NPC.Status.Strafing",NewTagName="NPC.Status.IsStrafing")
+GameplayTagList=(Tag="Actor.Action.Rotate",DevComment="")
+GameplayTagList=(Tag="Actor.State.IsRotating",DevComment="")
+GameplayTagList=(Tag="Character.Action.AttackCheck",DevComment="")
+GameplayTagList=(Tag="Character.Action.ChangeCombat",DevComment="")
+GameplayTagList=(Tag="Character.Action.DashAttack",DevComment="")
+GameplayTagList=(Tag="Character.Action.Defense",DevComment="")
+GameplayTagList=(Tag="Character.Action.HitCheck",DevComment="")
+GameplayTagList=(Tag="Character.Action.HitReact",DevComment="")
+GameplayTagList=(Tag="Character.Action.LinkedAction",DevComment="")
+GameplayTagList=(Tag="Character.Action.MeleeAttack",DevComment="")
+GameplayTagList=(Tag="character.Action.NativeHeal",DevComment="")
+GameplayTagList=(Tag="Character.Action.RangeAttack",DevComment="")
+GameplayTagList=(Tag="Character.Action.SkillE",DevComment="")
+GameplayTagList=(Tag="Character.Action.SkillQ",DevComment="")
+GameplayTagList=(Tag="Character.Action.SkillR",DevComment="")
+GameplayTagList=(Tag="Character.Action.SkillX",DevComment="")
+GameplayTagList=(Tag="Character.Buff.BaseBuff",DevComment="")
+GameplayTagList=(Tag="Character.Buff.RangedCharge",DevComment="")
+GameplayTagList=(Tag="Character.Skill.Around",DevComment="")
+GameplayTagList=(Tag="Character.Skill.DashAttack",DevComment="")
+GameplayTagList=(Tag="Character.Skill.Float",DevComment="")
+GameplayTagList=(Tag="Character.Skill.PiercingStrike",DevComment="")
+GameplayTagList=(Tag="Character.Skill.Stun",DevComment="")
+GameplayTagList=(Tag="Character.State.Invinsible",DevComment="")
+GameplayTagList=(Tag="Character.State.IsAttacking",DevComment="")
+GameplayTagList=(Tag="Character.State.IsChangeCombat",DevComment="")
+GameplayTagList=(Tag="Character.State.IsDead",DevComment="")
+GameplayTagList=(Tag="Character.State.IsDefense",DevComment="")
+GameplayTagList=(Tag="Character.State.IsDodge",DevComment="")
+GameplayTagList=(Tag="Character.State.IsFloat",DevComment="")
+GameplayTagList=(Tag="Character.State.IsGhost",DevComment="")
+GameplayTagList=(Tag="Character.State.IsHIt",DevComment="")
+GameplayTagList=(Tag="Character.State.IsJumping",DevComment="")
+GameplayTagList=(Tag="Character.State.IsKnockback",DevComment="")
+GameplayTagList=(Tag="Character.State.IsLinkedAction",DevComment="")
+GameplayTagList=(Tag="Character.State.IsMove",DevComment="")
+GameplayTagList=(Tag="Character.State.IsRangedCharge",DevComment="")
+GameplayTagList=(Tag="Character.State.IsSkilling",DevComment="")
+GameplayTagList=(Tag="Character.State.IsSprint",DevComment="")
+GameplayTagList=(Tag="Character.State.IsStun",DevComment="")
+GameplayTagList=(Tag="Character.State.IsTargeting",DevComment="")
+GameplayTagList=(Tag="Character.State.IsThunder",DevComment="")
+GameplayTagList=(Tag="Character.State.SkillCooldown",DevComment="")
+GameplayTagList=(Tag="Data.Damage",DevComment="")
+GameplayTagList=(Tag="Event.Character.Action.Around",DevComment="")
+GameplayTagList=(Tag="Event.Character.Action.AttackHitCheck",DevComment="")
+GameplayTagList=(Tag="Event.Character.Action.EndHitCheck",DevComment="")
+GameplayTagList=(Tag="Event.Character.Action.Float",DevComment="")
+GameplayTagList=(Tag="Event.Character.Action.HeavyHit",DevComment="")
+GameplayTagList=(Tag="Event.Character.Action.HitCheck",DevComment="")
+GameplayTagList=(Tag="Event.Character.Action.HitCheckMulti",DevComment="")
+GameplayTagList=(Tag="Event.Character.Action.LightHit",DevComment="")
+GameplayTagList=(Tag="Event.Character.Action.PlaySkill",DevComment="")
+GameplayTagList=(Tag="Event.Character.Action.SkillHitCheck",DevComment="")
+GameplayTagList=(Tag="Event.Character.Action.Stun",DevComment="")
+GameplayTagList=(Tag="Event.Character.Action.Thunder",DevComment="")
+GameplayTagList=(Tag="Event.Equip",DevComment="")
+GameplayTagList=(Tag="Event.Equip.Bow",DevComment="")
+GameplayTagList=(Tag="Event.Equip.DualBlade",DevComment="")
+GameplayTagList=(Tag="Event.Equip.Shield",DevComment="")
+GameplayTagList=(Tag="Event.Equip.Sword",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Ended",DevComment="")
+GameplayTagList=(Tag="Event.Player.ChangeCombatMode.DualBlade",DevComment="")
+GameplayTagList=(Tag="Event.Player.ChangeCombatMode.Idle",DevComment="")
+GameplayTagList=(Tag="Event.Player.ChangeCombatMode.Melee",DevComment="")
+GameplayTagList=(Tag="Event.Player.ChangeCombatMode.Range",DevComment="")
+GameplayTagList=(Tag="Event.Skill.Around",DevComment="")
+GameplayTagList=(Tag="Event.Skill.DashAttack",DevComment="")
+GameplayTagList=(Tag="Event.Skill.Float",DevComment="")
+GameplayTagList=(Tag="Event.Skill.Stun",DevComment="")
+GameplayTagList=(Tag="Event.UnEquip.Bow",DevComment="")
+GameplayTagList=(Tag="Event.UnEquip.DualBlade",DevComment="")
+GameplayTagList=(Tag="Event.UnEquip.Shield",DevComment="")
+GameplayTagList=(Tag="Event.UnEquip.Sword",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Character.AttackHit",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Character.AttackHit.Effect",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Character.AttackHit.Sound",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Character.ParryHit.Effect",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Character.ParryHit.Sound",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Character.RangeHit.Effect",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Character.RangeHit.Sound",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Character.StunHit.Effect",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Character.StunHit.Sound",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Character.ThunderHit",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Character.ThunderHit.Effect",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Character.ThunderHit.Sound",DevComment="")
+GameplayTagList=(Tag="NPC.Status.IsStrafing",DevComment="")
+GameplayTagList=(Tag="NPC.Status.IsUnderAttack",DevComment="")
+GameplayTagList=(Tag="NPC.Weapon",DevComment="")
+GameplayTagList=(Tag="Player.CombatMode.DualBlade",DevComment="")
+GameplayTagList=(Tag="Player.CombatMode.Idle",DevComment="")
+GameplayTagList=(Tag="Player.CombatMode.Melee",DevComment="")
+GameplayTagList=(Tag="Player.CombatMode.Range",DevComment="")
+GameplayTagList=(Tag="Player.State.IsSkillAwaitingConfirmation",DevComment="")
+GameplayTagList=(Tag="Player.State.IsUIMode",DevComment="")
+GameplayTagList=(Tag="Player.Weapon.Bow",DevComment="")
+GameplayTagList=(Tag="Player.Weapon.DualBladeL",DevComment="")
+GameplayTagList=(Tag="Player.Weapon.DualBladeR",DevComment="")
+GameplayTagList=(Tag="Player.Weapon.Shield",DevComment="")
+GameplayTagList=(Tag="Player.Weapon.Sword",DevComment="")
+GameplayTagList=(Tag="Shared.Ability.HitReact",DevComment="")
+GameplayTagList=(Tag="Shared.Event.HitReact",DevComment="")
+GameplayTagList=(Tag="Shared.Event.MeleeDamage",DevComment="")
+GameplayTagList=(Tag="Shared.Event.RangeDamage",DevComment="")
+GameplayTagList=(Tag="Shared.SetByCaller.BaseDamage",DevComment="")
+GameplayTagList=(Tag="Skill.Confirm.Instant",DevComment="")
+GameplayTagList=(Tag="Skill.Confirm.UserConfirm",DevComment="")

